### ISSUE TITLE
Mark Warlord

### ISSUE THREAD

**Issue by ZorgVomGork** [OnlineCodex/OnlineCodex#12]
- [x] Make it possible to mark the warlord in the army list
- [x] Make it possible to select Warlord traits directly on the Warlord
- [x] Add Warlord traits to Asuryani characters
- [x] Add Warlord traits to Drukahri characters
- [x] Add Warlord traits to Harlequin characters
- [x] Add Warlord traits to Chaos Daemon characters
- [x] Add Warlord traits to Chaos Space Marine characters
- [x] Add Warlord traits to Death Guard characters
- [x] Add Warlord traits to Thousand Sons characters
- [x] Add Warlord traits to Adeptus Custodes characters
- [x] Add Warlord traits to Adeptus Mechanicus characters
- [x] Add Warlord traits to Adeptus Militarum characters
- [x] Add Warlord traits to Blood Angel characters
- [x] Add Warlord traits to Dark Angel characters
- [x] Add Warlord traits to Deathwatch characters
- [x] Add Warlord traits to Grey Knight characters
- [x] Add Warlord traits to Space Marine characters
- [x] Add Warlord traits to Space Wolves characters
- [x] Add Warlord traits to Necron characters
- [x] Add Warlord traits to Ork characters
- [x] Add Warlord traits to Tyranid characters
- [x] Add Warlord traits to Tau characters

**Comment by chisui** [comment]
closed by #100
