### ISSUE TITLE
Astra Militarum bugs

### ISSUE THREAD

**Issue by spacecooky** [OnlineCodex/OnlineCodex#154]
- [x] Only the options appear in the list, without the name Chimera.
- [x] Bei den Auswahlen Tempestor Prime, Lord Commissar, Company Commander,  Platoon Commander, Infantry Squad, Tempestus Scions, Veterans und Commissar ist ein Fehler bezüglich der Nahkampfwaffen aufgetreten. Laut Codex dürfen diese Objekte von der Liste der Nahkampfwaffen erhalten (bei Scions der Tempestor und bei Veteranen und Infanteristen der Sergeant, dies sind laut Codex: Astra Militarum nur Power sword und Power fist. Alle ausser den beiden Kommissaren/Lord Kommissaren dürfen auch noch ein Chainsword erhalten. Der Sergeant der normalen Infanteristen darf sogar nur Chainsword und Power sword erhalten. Im Online Codex stehen aber auch Power maul und Power axe zur Auswahl. Das ist ein Fehler. In FAQs und CAs habe ich diesbezüglich auch keine Änderungen gefunden.

**Comment by chisui** [comment]
fixed by #156
