### ISSUE TITLE
Change Data Storage to a SQLite database

### ISSUE THREAD

**Issue by chimaira3003** [OnlineCodex/OnlineCodex#16]
The csv-based approach of data storage for unit entries could better be handled via a sqlite database. This database should include warlord traits, relics and pre-game stratagems (more relics and so) as well.
Saved files (army lists) could be sqlite databases as well.

**Comment by chisui** [comment]
We should use a `json` or `yaml` based file format for that in my opinion. It's important that the files are human readable and editable.

The benefits we would gain from an sqlite db would be having structured data and access speed. `json` and `yaml` would also provide structure and can easily be edited even by non programmers. The access speed is negligible in our usecase but if it would cause a bottle neck we would be better served to load the files at runtime into an in-memory-database like `h2`.
