### ISSUE TITLE
Bike Squad Chapter Approved cost correction

### ISSUE THREAD

**Issue by ryker8** [OnlineCodex/OnlineCodex#160]
Cost per unit is should be 21 Points instead of 23.

**Comment by chisui** [comment]
As far as I can tell the value of 23 is correct as @spacecooky says. 
Biker squad wargear (Codex: Space Marines, page 168)
21 points for each biker (Chapter approved 2018, page 125)
2 points for twin Boltgun (Codex: Space Marines, page 208)


@ryker8 Have we missed something or can this issue be closed?

**Comment by ryker8** [comment]
Tut mir leid, war mein Fehler hatte nicht gesehen das der Zwillingsbolter von den Punktekosten mit einbezogen war
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.01.19, 18:12, Philipp Dargel <notifications@github.com> schrieb:
As far as I can tell the value of 23 is correct as @spacecooky says.
Biker squad wargear (Codex: Space Marines, page 168)
21 points for each biker (Chapter approved 2018, page 125)
2 points for twin Boltgun (Codex: Space Marines, page 208)
@ryker8 Have we missed something or can this issue be closed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OnlineCodex/OnlineCodex","title":"OnlineCodex/OnlineCodex","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/OnlineCodex/OnlineCodex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chisui in #160: As far as I can tell the value of 23 is correct as @spacecooky says. \r\nBiker squad wargear (Codex: Space Marines, page 168)\r\n21 points for each biker (Chapter approved 2018, page 125)\r\n2 points for twin Boltgun (Codex: Space Marines, page 208)\r\n\r\n\r\n@ryker8 Have we missed something or can this issue be closed?"}],"action":{"name":"View Issue","url":"https://github.com/OnlineCodex/OnlineCodex/issues/160#issuecomment-452008559"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OnlineCodex/OnlineCodex/issues/160#issuecomment-452008559",
"url": "https://github.com/OnlineCodex/OnlineCodex/issues/160#issuecomment-452008559",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
