### ISSUE TITLE
Issue Techmarine

### ISSUE THREAD

**Issue by Armrond** [OnlineCodex/OnlineCodex#165]
The Costs for Servo-Arm and Servo-Harness is each 12 points too high.

**Comment by chisui** [comment]
in the current [OnlineCodex `8.10.0`](https://github.com/OnlineCodex/OnlineCodex/releases/tag/v8.10.0) release The costs are 11 points for the *Servo-Harness* and 0 for the *Servo-Arm*. These are the correct values as far as I know according to *Chapter Approved 2018*

**Comment by Armrond** [comment]
Apparently it was an older Version. So sorry, my mistake. I've downloaded the current version, renamed it, so I was sure to use it, and still I messed up. Sometimes  it's a little troublesome to keep older Versions, but I'd like to review older builds, and that doesn't always work with the newer releases.

**Comment by chisui** [comment]
All recent releases show a popup on startup if a newer Version exists (as long as you allow java to access the internet). Keeping older releases shouldn't be necessary anymore. You can download older releases from the releases page here.
Thank you for contributing anyway.

**Comment by Armrond** [comment]
Strangely enough, I realized the error occurred in the current Version. After reloading the right point costs were showing, then again not when launching via the Dock (on Mac), although I double-checked the alias was also linked to the current version. No Idea how that is possible. Thanks for the assistance nonetheless - and good to know with former releases available in any case.

**Comment by chisui** [comment]
Uhm, so you were able to reproduce the bug in `8.10.0`? The version is displayed in the Title.

Can you share the exact steps you took?

**Comment by chisui** [comment]
Ok, I will keep this issue closed. If you encounter this issue again in a reproducible manner feel free to report it. In general I would advise to not use the `*-new` naming scheme. Use the version number directly: `OnlineCodex-8.10.0.jar` and create a symlink `ln -s OnlineCodex-8.10.0.jar OnlineCodex.jar` and use the `OnlineCodex.jar` symlink to call the app.
