### ISSUE TITLE
Tau Empire 

### ISSUE THREAD

**Issue by ryker8** [OnlineCodex/OnlineCodex#232]
Commander XV86 Coldstar Battlesuit, wenn ich auf Waffen und Relikte klicke, kann ich dort 4 mal die High output burst cannon auswählen,die Waffen fällt aber nicht unter die Kategorie Fernkampfwaffen bei der Auswahl und kann daher nicht 4 mal genommen werden, sondern nur einmal

**Comment by Realturbo** [comment]
Vielen Dank für das Update.
Noch eine Anmerkung zu dieser Waffenauswahl:
Der Missle Pod kann auch nur zusammen mit der High Output Burst Cannon ersetzt werden. D.h. es ist z.B. nicht möglich die High Output Burst Cannon zusammen mit 3 Burst Cannons zu wählen.
