### ISSUE TITLE
Harlequins: Shadowseer has only 1 psychic choice instead of 2

### ISSUE THREAD

**Issue by wordman-D** [OnlineCodex/OnlineCodex#252]
Harlequins Codex Page 57

"This model can attempt to manifest two psychic powers in each friendly Psychic phase, and attempt to deny one psychic power in each enemy Psychic phase. It knows the Smite power and two psychic powers from the Phantasmancy discipline (pg 73)."

**Comment by Paul12191** [comment]
fixed the issue in PR https://github.com/OnlineCodex/OnlineCodex/pull/260

**Comment by chisui** [comment]
fixed by #260
