### ISSUE TITLE
CSM - Hellforged Contemptor / Leviathan Dreadnought

### ISSUE THREAD

**Issue by Narkjin** [OnlineCodex/OnlineCodex#39]
CSM - Hellforged Contemptor / Leviathan Dreadnought

If you chose a death- or chainclaw (or siege claw/drill @ leviathan) for the "upper" arm and a shooting weapon for the "lower" arm, you **cannot** chose any secondary weapon (hellflamer, combi-bolter etc.) for the claw. If you switch the loadout (shooting -> upper arm, claw lower arm), you are **able to chose two** secondary weapons.

**Comment by chisui** [comment]
Thank you for reporting. We'll look into it.

**Comment by chisui** [comment]
Closed by #77
