### ISSUE TITLE
Change versioning Scheme

### ISSUE THREAD

**Issue by chisui** [OnlineCodex/OnlineCodex#40]
We should change the versioning scheme from `<year>.<month>.<day>` to something more sensible. Using the date as a version number makes it pretty hard to plan releases so I would suggest some other versioning scheme.

I am proposing something like [Semver](https://semver.org/). Where the *major* Version is the number of the current WH40k edition. The *minor* will be incremented by each normal release. The *update* should only be used for hotfix releases when the last *minor* release is broken.

Does anyone have a better versioning scheme or wants to continue with the old one?

**Comment by spacecooky** [comment]
We already talked about it. I share your opinion and we should do it this way.

**Comment by chisui** [comment]
This requires a change to the version checker.
