### ISSUE TITLE
Deffdreads

### ISSUE THREAD

**Issue by Wastel1983** [OnlineCodex/OnlineCodex#62]
waffenauswahl funktioniert nicht

**Comment by chisui** [comment]
What exactly doesn't work?

I can select weapons, their points are added to the total and all choices are are present in the list view.

**Comment by spacecooky** [comment]
It's working.
You have to deselect the standard weapons first, by right-clicking them.
 But another approach is more suitable in this case, as you could end up without selected weapons and without any kind of warning that you should actually select them.

**Comment by chisui** [comment]
fixed by #64
