### ISSUE TITLE
Chaos Bugs

### ISSUE THREAD

**Issue by spacecooky** [OnlineCodex/OnlineCodex#74]
- [x] Lord Arkos --> kostet 124p mit Bewaffnung
- [x] Necrosius --> Death Guard; kann auch als <LEGION> The Tainted gespeilt werden --> ist ein CSM Renegade Chapter
- [x] Necrosius --> Fehlermeldung „Klasse nicht gefunden"
- Daemon Prince --> kostet 146p, mit Wafffe 156p (nicht 166p)(falsche Angabe, da 2 Waffen)
- Sorcerer + Termi-Armour --> kostet nach CA’18 122p (Falsche Angabe, im CA 120p)
- [x] Lord of Contagion --> ist Death Guard
- [x] Malignent Plaguecaster --> ist Death Guard
- [x] Chaos Hellwrightz --> kostet 133p mit Ausrüstung
- [x] Chaos Hellwright on Drak Abeyant --> 178p mit Ausrüstung
- [x] Uraka the Warfiens --> ist ein Chaos Daemon
- [x] Samus --> ist ein Chaos Daemon
- [x] Mamon Transfigured --> Death Gurad; kann auch als <LEGION> The Tainted gespeilt werden --> ist ein CSM Renegade Chapter
- [x] Cor’Bax Utterblieght --> ist ein Chaos Daemon
- [x] Poxwalker --> Death Guard
- [x] Tzaangor --> Thousand Sons
- [x] Chaos Decimator
- [x] --> Soulburner petard 60p
- [x] --> Decimator siege claw + Hellflamer zusammen 47p
- [x] Hellforged Dreadclaw Droppod --> 130p nach CA‘18
- [x] Hellforged Kharybdis Assault Claw --> 375 nach CA’18
- [x] Plague Toads of Nurgle --> ist ein Chaos Daemon
- [x] Pox Riders of Nurgle --> ist ein Chaos Daemon
- [x] Plague Hulk of Nurgle à ist ein Chaos Daemon
- [x] Hellforged Predator
- [x] -->ist eine Elite-Auswahl
- [x] --> 95p ohne Bewaffnung
--> Magma-melta cannon 52p nach CA‘18 (falsche Angabe, 70 nach CA)
- [x] Hellforged Leviathan Dreadnought
- [x] --> Meltaguns und Hellforged siege claws können nur zusammen ausgeatuischt werden
- [x] --> Hellforged siege claw (single/pair) 55/65p

**Comment by chisui** [comment]
closed by #79
