### ISSUE TITLE
Deathwatch Points and Equipements

### ISSUE THREAD

**Issue by ZorgVomGork** [OnlineCodex/OnlineCodex#8]
- [x] Sergeant can use heavy weapons (couldn't find that option in the Codex)
- [x] Sergeant can choose two "normal" weapons (e.g. Storm Bolter and Power Sword)
- [x] When a Veteran gets a Hammer, he can also choose additional equipment (which shouldn't be possible)
- [x] You can equip more than four Veterans with heavy weapons
- [x] You can build a Veteran squad below power 5. Codex states, that a Sergeant and Blackshield can each replace a single Veteran. Currently it's possible to only choose three Veterans or additionally choose Vanguards/Terminators/...
- [x] Sergeant currently can't equip Xeno-Phase-Blade as CC weapon.
- [x] Deathwatch Terminators cost 31 instead of 26 points.

**Comment by chisui** [comment]
fixed by #83
