### ISSUE TITLE
Mark CSM index units

### ISSUE THREAD

**Issue by spacecooky** [OnlineCodex/OnlineCodex#80]
The following CSM units shall be marked as [INDEX] units

- [x] Chaos Lord on Bike
- [x] Chaos Lord on Juggernaut of Khorne (auch World Eaters)
- [x] Chaos Lord on Disc of Tzeentch
- [x] Chaos Lord on Palanquin of Nurgle (auch Death Guard)
- [x] Chaos Lord on Steed of Slaanesh (auch Noise Marines)
- [x] Sorcerer on Bike
- [x] Sorcerer on Disc of Tzeentch (auch Thgousand Sons)
- [x] Sorcerer on Palanquin of Nurgle (auch Death Guard, ACHTUNG: hat immer die Psidisziplin Heretic Astartes, nicht die der Death Guard)
- [x] Sorcerer on Steed of Slaanesh (auch Noise Marines)

**Comment by chisui** [comment]
closed by #81
