### ISSUE TITLE
Complete Chaosdaemons

### ISSUE THREAD

**Issue by spacecooky** [OnlineCodex/OnlineCodex#99]
- [x] Divide Chaosdaemon army lists depending on the chosen god.
- [x] Add relics
- [x] Check psykers
- [x] Clean up refreshen methods

**Comment by Andreakasniperjack** [comment]
1. Epidemus default warlord trait works, but if you choose another warlord e.g. posbringer you can just choose the first 4 Warlord Traits. None else. Is it possible that these are linked to the monogod option. Yes i see. But i think it should be choosable too, if you dont choose a monogod option. 
2. The nurglings have no value in this version.

**Comment by spacecooky** [comment]
1. I'm working on it. That is one of the points I already found and figured out. Initially I thought you had to take a monogod army for beeing able to chose monogod traits, like it's the case in some other armies with sub factions.
2. Thanks, that will also be fixed in the next update.

**Comment by chisui** [comment]
fixed by #115
